Convert database migration scripts to vanilla JS
These files shouldn't be compiled as part of the actual app,
so just convert them to JS so we can run them directly with `node`.

Also, running `npm run test` errors when these are TypeScript
files:

error TS6059: File
'C:/Users/zhaow/stuff/projects/sgexams-bot/database/init.ts' is not
under 'rootDir' 'C:/Users/zhaow/stuff/projects/sgexams-bot/src'.
'rootDir' is expected to contain all source files.

error TS6059: File
'C:/Users/zhaow/stuff/projects/sgexams-bot/database/migrate.ts' is not
under 'rootDir' 'C:/Users/zhaow/stuff/projects/sgexams-bot/src'.
'rootDir' is expected to contain all source files.